### PR TITLE
Remove unnecessary files from package

### PR DESCRIPTION
**Pull request by Jake-Shadle**

### CODE REVIEW

**Review by djc — APPROVED** [review]
Any particular motivation for these changes? IIRC some distro packagers like to run tests from the packages.

**Comment by Jake-Shadle** [comment]
Ahh, I wasn't aware distro packagers packaged library crates like that, I guess I'll remove that one.

The motivation was mainly that the crate package currently includes the `scripts/generate-certificate.sh` which is both unnecessary for downstream users, and triggers a new check I'm adding to cargo-deny to resolve https://github.com/EmbarkStudios/cargo-deny/issues/43

**Comment by djc** [comment]
So are you going to submit PRs for all crates that are upstream of Embark crates? 😄

**Comment by Jake-Shadle** [comment]
Possibly...

**Pull request merged**
