### PR TITLE
Update generate-certificate.sh to write certs etc. to current dir

### PR DESCRIPTION
**Pull request by ghenry**
Caught me out a few times now, so submitting this PR.

Thanks!

### CODE REVIEW

**Comment by ghenry** [comment]
This works as expected now:

```
RUST_BACKTRACE=1 cargo run --example server -- 127.0.0.1:8000 --cert scripts/cert.pem --key scripts/server.key.pem 
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/examples/server '127.0.0.1:8000' --cert scripts/cert.pem --key scripts/server.key.pem`
```

**Comment by djc** [comment]
I don't consider `generate-certificate.sh` to be a public artifact, so I don't think we want to support it by catering to your needs (which, as discussed in #76, are definitely not in scope for this script).

**Comment by ghenry** [comment]
For writing the certs out to a directory you're working in? That's not a very complicated need and should have been the default IMHO. I think of this as a bug fix, but your call obviously.

**Comment by djc** [comment]
I mean that you should not be using this script, as it is strictly intended for this repository's maintainers to help maintain the test suite, and not for anything else. "bug fix" implies that there is expected behavior to verify the actual behavior against, and I am arguing the behavior is unspecified. If you want to make changes, please maintain your own copy.

**Comment by ghenry** [comment]
Understood, thanks.

**Comment by cpu** [comment]
@ghenry Thanks for the PR. As I mentioned on the other issue thread I think we should delete that script entirely. It's never even been used for this repo's code. I've put up a PR doing so and replaced it with a pure Rust alternative for generating our test certificates: https://github.com/rustls/tokio-rustls/pull/80 You might find the new `rcgen` based code useful as inspiration but echoing djc's point we wouldn't consider updates to make that integration test more generally useful outside of this repo. It's purely scaffolding for our own testing purposes.

If you're especially keen to have your bash script fix live on it looks like [`tokio/tls`](https://github.com/tokio-rs/tls) (for the non-Rustls maintained `native-tls`) [still uses the script]( https://github.com/tokio-rs/tls/blob/02c1aeb7001525f4aa71e07312f8519872dc638a/tokio-native-tls/scripts/generate-certificate.sh). Perhaps that repo would take a PR (_though other updates to the same area look to be stale: https://github.com/tokio-rs/tls/pull/153_)

**Comment by ghenry** [comment]
Thanks for the helpful comments @cpu Much appreciated.

I'll take a look. Certainly not a great first impression for a contribution, but it's my own fault for not asking @djc or similar first, so that's on me.

Have a great weekend!

**Pull request closed without merging**
