### PR TITLE
Fix: Check for ErrorKind::WouldBlock in LazyConfigAcceptor

### PR DESCRIPTION
**Pull request by jbr**
Similar to #47

### CODE REVIEW

**Review by djc — APPROVED** [review]

**Comment by djc** [comment]
Since this seems a little finicky, could you add a test?

**Comment by jbr** [comment]
Good call with the test, the original implementation didn't handle the possibility that the write buffer was too small to fit the whole alert

**Review by djc — APPROVED** [review]

**Review by ctz — APPROVED** [review]
Thanks for catching these!

**Comment by djc** [comment]
(Needs a rebase now.)

**Review by quininer — APPROVED** [review]
LGTM

**Comment by jbr** [comment]
Rebased

**Comment by quininer** [comment]
Thank you!

**Pull request merged**
