### PR TITLE
examples: prefer pemfile::private_key

### PR DESCRIPTION
**Pull request by cpu**
Using [`rustls_pemfile::rsa_private_keys`](https://docs.rs/rustls-pemfile/latest/rustls_pemfile/fn.rsa_private_keys.html) is overly specific, limiting use to just RSA keys with PKCS#1 encoding.

This commit switches to using [`rustls_pemfile::private_key`](https://docs.rs/rustls-pemfile/latest/rustls_pemfile/fn.private_key.html) which is tailor made for loading one private key in any of the supported formats.

Updates https://github.com/rustls/tokio-rustls/issues/76

### CODE REVIEW

**Comment by cpu** [comment]
> CI / MSRV (pull_request) Failing after 1m
> ...
> error: package `cc v1.1.0` cannot be built because it requires rustc 1.67 or newer, while the currently active rustc version is 1.63.0

This repo doesn't check in a lockfile, but it probably should? Fixing this sort of MSRV min version build error without is a bit annoying. @djc WDYT?

**Comment by djc** [comment]
+1.

**Comment by cpu** [comment]
> +1.

https://github.com/rustls/tokio-rustls/pull/78

**Review by djc — APPROVED** [review]

**Comment by cpu** [comment]
@quininer Same thing here :-) Merging w/ one approval, but with the expectation that if you have feedback I will revisit.

**Pull request merged**
